### ISSUE TITLE
Cannot access the configuration

### ISSUE THREAD

**Issue by Alixollo** [replaceitem/symbol-chat#33]
It is impossible to access to the mod configuration through the modmenu mod's GUI, nor from the plugin's UI.

![image](https://github.com/replaceitem/symbol-chat/assets/89808322/38b72370-c434-40cc-9acb-c3553d16802f)

Trying to access from the mod's gui crashes the game

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-06-06 10:19:37
Description: mouseClicked event handler

java.lang.NoClassDefFoundError: Could not initialize class me.shedaniel.autoconfig.AutoConfig$ClientOnly
	at me.shedaniel.autoconfig.AutoConfig.getConfigScreen(AutoConfig.java:91)
	at net.replaceitem.symbolchat.config.ClothConfigProvider.getConfigScreen(ClothConfigProvider.java:74)
	at net.replaceitem.symbolchat.gui.widget.symbolButton.SettingsButtonWidget.method_25348(SettingsButtonWidget.java:31)
	at net.minecraft.class_339.method_25402(class_339.java:187)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_408.method_25402(class_408.java:157)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:207)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218)
	at net.minecraft.class_1041.method_15998(class_1041.java:393)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by replaceitem** [comment]
Do you have [ClothConfig](https://modrinth.com/mod/cloth-config) installed? It is required for configuration of the mod
