### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by sternschnaube** [replaceitem/symbol-chat#34]
Random crash while I tried to open the chat.

java.lang.NullPointerException: Cannot invoke "net.replaceitem.symbolchat.font.FontProcessor.convertString(String)" because "fontProcessor" is null
	at net.minecraft.class_408$1.method_1867(class_408.java:520)
	at net.minecraft.class_342.method_25400(class_342.java:354)
	at net.minecraft.class_4069.method_25400(class_4069.java:86)
	at net.minecraft.class_408.method_25400(class_408.java:3047)
	at dev.architectury.impl.fabric.ScreenInputDelegate$DelegateScreen.method_25400(ScreenInputDelegate.java:42)
	at net.minecraft.class_309.method_1458(class_309.java:467)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_309.method_1457(class_309.java:467)
	at net.minecraft.class_309.method_22677(class_309.java:478)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22675(class_309.java:478)
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by replaceitem** [comment]
Fixed in [1.0.1](https://modrinth.com/mod/symbol-chat/version/1.0.1)

**Comment by sternschnaube** [comment]
Thanks alot!!
