### ISSUE TITLE
incompatibility with axiom

### ISSUE THREAD

**Issue by envizar** [replaceitem/symbol-chat#43]
reporting it here cuz `symbol-chat-1.21-1.2.3.jar` in error
lemme know if it's an axiom problem and I need to report this to axiom devs

## Versions
Fabric loader 0.15.11
Minecraft 1.21
Axiom 3.1.0
Symbol Chat 1.2.3

## How to reproduce
1. Install axiom and symbol chat
2. Open game, open a world and just open chat
3. Game crashes

## Error from logs
```
[17:26:21] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Unknown Source) ~[?:?]
	at java.base/java.util.ArrayList.get(Unknown Source) ~[?:?]
	at net.replaceitem.symbolchat.gui.SymbolSelectionPanel.getSymbolTab(SymbolSelectionPanel.java:65) ~[symbol-chat-1.21-1.2.3.jar:?]
	at net.replaceitem.symbolchat.gui.SymbolSelectionPanel.getCurrentTab(SymbolSelectionPanel.java:69) ~[symbol-chat-1.21-1.2.3.jar:?]
	at net.replaceitem.symbolchat.gui.SymbolSelectionPanel.<init>(SymbolSelectionPanel.java:51) ~[symbol-chat-1.21-1.2.3.jar:?]
	at net.minecraft.class_408.addSymbolChatComponents(class_408.java:1068) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.handler$djo01b$symbol-chat$onInit(class_408.java:535) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_25426(class_408.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1143) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29041(class_310.java:1100) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2088) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1938) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.
```

**Comment by replaceitem** [comment]
Do you have any resourcepacks or mods that could mess with resourcepacks? It seems like the mod could not load any tabs from the resources, which shouldn't happen in the default configuration
